# Dockerfile.economic_enrichment_worker
FROM python:3.9-slim-buster
WORKDIR /app
COPY parser/requirements_parse.txt .
RUN pip install --no-cache-dir -r requirements_parse.txt
COPY . .
CMD ["python", "/app/parser/economic_parser/economic_enrichment_worker.py"]