# Dockerfile.analysis_worker
FROM python:3.9-slim-buster
WORKDIR /app
COPY ML/requirements_ml.txt .
RUN pip install --no-cache-dir -r requirements_ml.txt
COPY . .
CMD ["python", "/app/ML/analysis_worker.py"] 